model_name: "almanach/camembertav2-base"

path2json: "/home/labat/granddebat/data/gdnannotanalysis-main/gold/AS_EXTRACTION/gold.jsonl"
model_output_dir: "/home/labat/granddebat/as_extraction/checkpoints"

num_epochs: 3
batch_size: 4
lr: "5e-5"
max_span_len: 250
type_loss_weight: 1.0